# 1. DATABASE CONNECTION
spring.datasource.url=jdbc:mysql://localhost:3306/codeb_ims
spring.datasource.username=root
spring.datasource.password=Saumay@05

# 2. HIBERNATE SETTINGS
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 3. BREVO API SETTINGS (Bypasses Firewall)
# We pull the key from Railway variables to prevent GitHub errors
codeb.brevo.apikey=${BREVO_API_KEY}

# Your verified sender email
codeb.brevo.sender=dhanshrikalshetti2005@gmail.com